# Generated by Django 4.2.4 on 2023-09-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='type',
            field=models.CharField(choices=[('شرعي', 'شرعي'), ('علمي', 'علمي')], default='شرعي', max_length=10, verbose_name='نوع الشهادة'),
        ),
    ]
